name: apiverve_isbnvalidator
description: ISBN Validator is a comprehensive tool for validating and parsing ISBN-10 and ISBN-13 book identification numbers. It validates checksums and provides detailed information about each ISBN component.
version: 1.1.14
homepage: https://apiverve.com/marketplace/isbnvalidator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/isbnvalidator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
