// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ISBNValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("valid")]
        public bool Valid { get; set; }

        [JsonProperty("isbn")]
        public string Isbn { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("normalized")]
        public string Normalized { get; set; }

        [JsonProperty("formatted")]
        public string Formatted { get; set; }

        [JsonProperty("checksum_valid")]
        public bool ChecksumValid { get; set; }

        [JsonProperty("prefix")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Prefix { get; set; }

        [JsonProperty("group")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Group { get; set; }

        [JsonProperty("publisher")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Publisher { get; set; }

        [JsonProperty("title")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Title { get; set; }

        [JsonProperty("check_digit")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long CheckDigit { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }
    }
}
